version: '3.8'    

services:
  db-postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: superheroidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: superheroidb4
            MONGO_INITDB_ROOT_USERNAME: mongodbteste
            MONGO_INITDB_ROOT_PASSWORD: 12345678asdasd
        ports:
            - 27018:27017
        volumes:
            - ./mongo-db-data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  db:
    driver: bridge

volumes:
  db:
  mongo-db-data: