version: '3.8'    
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db-postgres
      - mongodb
    volumes:
      - ./src:/app/src  
  db-postgres:
    image: postgres
    environment:
      POSTGRES_DB: superheroidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - /db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  mongodb:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_DATABASE: superheroidb4
            MONGO_INITDB_ROOT_USERNAME: mongodbteste
            MONGO_INITDB_ROOT_PASSWORD: 12345678asdasd
        ports:
            - 27017:27017
        volumes:
            - ./mongo-db-data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  db:
  mongo-db-data: