name: CD Pipeline

on:
  workflow_run:
    workflows:  ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Login Docker
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Pull Docker image
      run: sudo docker pull ffcsantos2001/superheroirepos:latest
    - name: Deletar container docker antigo
      run: sudo docker rm -f superheroi-container || true
    - name: Rodar docker container
      run: sudo docker run -d -p 8080:3000 --name superheroi-container ffcsantos2001/superheroirepos
